 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:10
     branches:
       only:
         - master
     steps:
       - add_ssh_keys:
           fingerprints:
             - "12:84:88:57:29:d4:42:eb:ed:54:0f:32:b8:d6:44:2c"
       - checkout
       - restore_cache:
           key: dependencies_imooc
       - run: 
           name: Install
           command: npm install
       - save_cache:
           key: dependencies_imooc
           paths:
             - node_modules
       - run:
           name: Build
           command: npm run build
       - run:
           name: Prepare shell commands
           # shell chmod +x 赋予执行权限
           # 执行shell脚本
           command: chmod + x scripts/deploy.sh
       - run:
           name: Run Deploy to Github pages
           command: ./scripts/deploy.sh